version: '3.11'

networks:
  default:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME}

services:
  sagi:
    image: sagicuhk/sagi:latest
    container_name: "${USERNAME}_sagi-dev"
    volumes:
      - ${SAGI_DIR}:/chatbot
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
    cap_add:
      - SYS_ADMIN
    command: ["tail", "-f", "/dev/null"]  # keep docker running
    restart: unless-stopped
    deploy:
      mode: global
    ports:
      - "8001"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_PATH=${SAGI_DIR}