[model_clients]
  [model_clients.orchestrator_client]
    model = "gpt-4o-mini"
    base_url = "${OPENAI_BASE_URL}"
    api_key = "${OPENAI_API_KEY}"
    max_tokens = 16000

  [model_clients.planning_client]
    model = "gpt-4o-mini"
    base_url = "${OPENAI_BASE_URL}"
    api_key = "${OPENAI_API_KEY}"
    max_tokens = 16000
    
  [model_clients.reflection_client]
    model = "gpt-4o-mini"
    base_url = "${OPENAI_BASE_URL}"
    api_key = "${OPENAI_API_KEY}"
    max_tokens = 16000
  
  [model_clients.code_client]
    model = "gpt-4.1-2025-04-14"
    base_url = "${OPENAI_BASE_URL}"
    api_key = "${OPENAI_API_KEY}"
    max_tokens = 16000